apiVersion: autoscaling.k8s.io/v1alpha1
kind: Hvpa
metadata:
  annotations:
    "hpa-controller": "hvpa"
    #"enable-vertical-scale-down": "true"
  labels:
    controller-tools.k8s.io: "1.0"
  name: hvpa-sample
spec:
  scaleUpStabilizationWindow: "2m"
  scaleDownStabilizationWindow: "3m"
  minCpuChange:
    value: 20m
    percentage: 80
  minMemChange:
    value: 100M
    percentage: 80
  hpaTemplate:
    maxReplicas: 7
    minReplicas: 1
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
  vpaTemplate:
    resourcePolicy:
      containerPolicies:
      - MinAllowed:
          memory: 400Mi
        containerName: resource-consumer
        maxAllowed:
          memory: 3000Mi
  weightBasedScalingIntervals:
    - vpaWeight: 0
      startReplicaCount: 1
      lastReplicaCount: 2
    - vpaWeight: 0.5
      startReplicaCount: 3
      lastReplicaCount: 5
    - vpaWeight: 0.6
      startReplicaCount: 6
      lastReplicaCount: 7
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-consumer
