apiVersion: autoscaling.k8s.io/v1alpha1
kind: Hvpa
metadata:
  annotations:
    "hpa-controller": "hvpa"
  labels:
    controller-tools.k8s.io: "1.0"
  name: hvpa-sample
spec:
  replicas: 1
  scaleUpStabilization:
    duration: "2m"
    minCpuChange:
      value: 20m
      percentage: 80
    minMemChange:
      value: 100M
      percentage: 80
  scaleDownStabilization:
    duration: "2m"
    minCpuChange:
      value: 20m
      percentage: 80
    minMemChange:
      value: 100M
      percentage: 80
  hpa:
    template:
      creationTimestamp: null
      spec:
        maxReplicas: 3
        minReplicas: 1
        metrics:
        - resource:
            name: memory
            target:
              averageUtilization: 70
              type: Utilization
          type: Resource
        - resource:
            name: cpu
            target:
              averageUtilization: 60
              type: Utilization
          type: Resource
    updatePolicy:
      updateMode: ScaleUp
  vpa:
    template:
      creationTimestamp: null
      spec:
        resourcePolicy:
          containerPolicies:
          - containerName: resource-consumer
            maxAllowed:
              memory: 3000Mi
            minAllowed:
              memory: 400Mi
    updatePolicy:
      updateMode: "On"
  weightBasedScalingIntervals:
    - vpaWeight: 0
      startReplicaCount: 1
      lastReplicaCount: 2
    - vpaWeight: 0.5
      startReplicaCount: 3
      lastReplicaCount: 5
    - vpaWeight: 0.6
      startReplicaCount: 6
      lastReplicaCount: 7
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-consumer
