apiVersion: autoscaling.k8s.io/v1alpha1
kind: Hvpa
metadata:
  annotations:
    "hpa-controller": "hvpa"
  name: hvpa-sample
  namespace: default
spec:
  replicas: 1
  scaleUpStabilization:
    duration: "2m"
    minCpuChange:
      value: 20m
      percentage: 80
    minMemChange:
      value: 100M
      percentage: 80
  scaleDownStabilization:
    duration: "2m"
    minCpuChange:
      value: 20m
      percentage: 80
    minMemChange:
      value: 100M
      percentage: 80
  hpa:
    selector:
      matchLabels:
        key1: value1
    template:
      metadata:
        labels:
          key1: value1
      spec:
        maxReplicas: 3
        minReplicas: 1
        metrics:
        - resource:
            name: memory
            targetAverageUtilization: 70
          type: Resource
        - resource:
            name: cpu
            targetAverageUtilization: 60
          type: Resource
    updatePolicy:
      updateMode: ScaleUp
  vpa:
    selector:
      matchLabels:
        key2: value2
    template:
      metadata:
        labels:
          key2: value2
      spec:
        resourcePolicy:
          containerPolicies:
            - containerName: resource-consumer
              maxAllowed:
                memory: 3000Mi
              minAllowed:
                memory: 400Mi
    updatePolicy:
      updateMode: "On"
  weightBasedScalingIntervals:
    - vpaWeight: 0
      startReplicaCount: 1
      lastReplicaCount: 2
    - vpaWeight: 50
      startReplicaCount: 3
      lastReplicaCount: 5
    - vpaWeight: 60
      startReplicaCount: 6
      lastReplicaCount: 7
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-consumer
