apiVersion: autoscaling.k8s.io/v1alpha1
kind: Hvpa
metadata:
  # Comment below annotation if you want kube-controller-manager to act on HPA's recommendation instead of hvpa-controller
  annotations:
    "hpa-controller": "hvpa"
  name: hvpa-sample
spec:
  scaleUpStabilization:
    duration: "2m"
    minCpuChange:
      value: 20m
      percentage: 80
    minMemChange:
      value: 100M
      percentage: 80
  scaleDownStabilization:
    duration: "3m"
    minCpuChange:
      value: 20m
      percentage: 80
    minMemChange:
      value: 100M
      percentage: 80
  hpa:
    selector:
      matchLabels:
        key1: value1
    template:
      metadata:
        labels:
          key1: value1
      spec:
        maxReplicas: 3
        minReplicas: 1
        metrics:
        - resource:
            name: memory
            targetAverageUtilization: 70
          type: Resource
        - resource:
            name: cpu
            targetAverageUtilization: 60
          type: Resource
    updatePolicy:
      updateMode: "Auto"
  vpa:
    selector:
      matchLabels:
        key2: value2
    limitsScaleParams:
      cpu:
        percentage: 80
        value: "2"
      memory:
        percentage: 80
        value: 3G
    template:
      metadata:
        labels:
          key2: value2
      spec:
        resourcePolicy:
          containerPolicies:
            - containerName: resource-consumer
              maxAllowed:
                memory: 3000Mi
              minAllowed:
                memory: 400Mi
    updatePolicy:
      updateMode: "scaleUp"
  weightBasedScalingIntervals:
    - vpaWeight: 0
      startReplicaCount: 1
      lastReplicaCount: 2
    - vpaWeight: 1
      startReplicaCount: 3
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-consumer
